# Generated by Django 2.2.2 on 2019-06-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='add_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='add_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='add_date',
            new_name='date_added',
        ),
    ]
