# Generated by Django 2.2.2 on 2019-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20190623_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('COM', 'computer'), ('MATH', 'math'), ('PHYSICS', 'physics'), ('OTHER', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_method',
            field=models.CharField(choices=[('SH', 'shipping'), ('OF', 'offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PR', 'processing'), ('CO', 'completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(default='no description'),
        ),
    ]
